name: daily-digest

on:
  schedule:
    - cron: "30 3 * * *"  # 09:00 Asia/Kolkata (GitHub cron is UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: techideas

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run digest
        run: npm run digest